# -*- coding: utf-8 -*-
"""
ES -> EN словарь IT / dev сленга (Испанский язык).

Включает Spanglish-дериваты (pushear, commitear), фонетические особенности
испанского произношения английских терминов (yeison, escuel) и стандартный сленг.
"""

import re

TERMS = {
    # Продвинутые фразы и конструкции
    'programación orientada a objetos': 'object-oriented programming',
    'interfaz de línea de comandos': 'command line interface',
    'expresión regular': 'regular expression',
    'punto de interrupción': 'breakpoint',
    'solicitud de extracción': 'pull request',
    'devuelve un booleano': 'returns boolean',
    'devuelve un arreglo': 'returns array',
    'devuelve una cadena': 'returns string',
    'devuelve un objeto': 'returns object',
    'devuelve un entero': 'returns integer',
    'lista doblemente enlazada': 'doubly linked list',
    'variable de entorno': 'environment variable',
    'imprimir en consola': 'console.log',
    'imprime en consola': 'console.log',
    'diseño responsivo': 'responsive design',
    'efecto secundario': 'side effect',
    'componente estilizado': 'styled-component',
    'prueba de integración': 'integration test',
    'desestructuración': 'destructuring',
    'prueba de extremo a extremo': 'end-to-end test',
    'función de orden superior': 'higher-order function',
    'servidor local': 'localhost',
    'lista enlazada': 'linked list',
    'árbol binario': 'binary tree',
    'clave privada': 'private key',
    'clave pública': 'public key',
    'interfaz de usuario': 'user interface',
    'código fuente': 'source code',
    'número flotante': 'float',
    'número entero': 'integer',
    'por defecto': 'default',
    'hacer un commit': 'commit',
    'hacer un push': 'push',
    'hacer un pull': 'pull',
    'hacer deploy': 'deploy',
    'rama principal': 'main branch',
    'en tiempo real': 'real-time',
    'función pura': 'pure function',
    'función flecha': 'arrow function',
    'prueba unitaria': 'unit test',

    # Spanglish глаголы (все формы, которые может выдать STT)
    'hardcodeado': 'hardcoded',
    'hardcodear': 'hardcode',
    'refactorear': 'refactor',
    'refactorizar': 'refactor',
    'debuggear': 'debug',
    'debuggea': 'debug',
    'debuggeando': 'debugging',
    'commitear': 'commit',
    'commitea': 'commit',
    'commiteado': 'committed',
    'deployar': 'deploy',
    'deploya': 'deploy',
    'deployado': 'deployed',
    'deployando': 'deploying',
    'pushear': 'push',
    'pushea': 'push',
    'pusheado': 'pushed',
    'pusheando': 'pushing',
    'pullear': 'pull',
    'pullea': 'pull',
    'pulleado': 'pulled',
    'pulleando': 'pulling',
    'mergear': 'merge',
    'mergea': 'merge',
    'mergeado': 'merged',
    'mergeando': 'merging',
    'buildear': 'build',
    'buildea': 'build',
    'buildeado': 'built',
    'buildeando': 'building',
    'clonar': 'clone',
    'clona': 'clone',
    'clonado': 'cloned',
    'parsear': 'parse',
    'parsea': 'parse',
    'parseado': 'parsed',
    'customizar': 'customize',
    'upgradear': 'upgrade',
    'loguearse': 'login',
    'loguear': 'login',
    'desloguear': 'logout',
    'desloguearse': 'logout',
    'scrollear': 'scroll',
    'clickear': 'click',
    'cliquear': 'click',
    'castear': 'cast',
    'testear': 'test',
    'testea': 'test',
    'testeando': 'testing',
    'resetear': 'reset',
    'formatear': 'format',
    'optimizar': 'optimize',
    'inicializar': 'initialize',
    'ejecutar': 'run',

    # Фонетические искажения испанского STT (испанский акцент)
    'llavascrit': 'JavaScript',
    'llavascri': 'JavaScript',
    'yavascrit': 'JavaScript',
    'yavascri': 'JavaScript',
    'tayscrit': 'TypeScript',
    'taiscrit': 'TypeScript',
    'tayscri': 'TypeScript',
    'taiscri': 'TypeScript',
    'reac': 'React',
    'riact': 'React',
    'gijab': 'GitHub',
    'gija': 'GitHub',
    'gitja': 'GitHub',
    'gitjab': 'GitHub',
    'gitla': 'GitLab',
    'gila': 'GitLab',
    'doker': 'Docker',
    'kuber': 'Kubernetes',
    'cubernetes': 'Kubernetes',
    'yeison': 'JSON',
    'jason': 'JSON',
    'escuel': 'SQL',
    'esquele': 'SQL',
    'esecuele': 'SQL',
    'garlik': 'GraphQL',
    'grafcuel': 'GraphQL',
    'bacend': 'backend',
    'baquend': 'backend',
    'fronend': 'frontend',
    'estayl': 'style',
    'espríng': 'Spring',
    'anguilar': 'Angular',
    'fech': 'fetch',
    'fechar': 'fetch',
    'becap': 'backup',
    'guit': 'git',

    # Существительные, сленг и базовые концепты
    'base de datos': 'database',
    'middleware': 'middleware',
    'endpoint': 'endpoint',
    'endpoints': 'endpoints',
    'petición': 'request',
    'respuesta': 'response',
    'encabezado': 'header',
    'encabezados': 'headers',
    'repositorio': 'repository',
    'repo': 'repo',
    'repos': 'repos',
    'bucle': 'loop',
    'lazos': 'loops',
    'rama': 'branch',
    'ramas': 'branches',
    'entorno': 'environment',
    'hilos': 'threads',
    'fichero': 'file',
    'archivo': 'file',
    'archivos': 'files',
    'carpeta': 'folder',
    'directorio': 'directory',
    'librería': 'library',
    'librerías': 'libraries',
    'biblioteca': 'library',
    'promesa': 'Promise',
    'promesas': 'promises',
    'asíncrono': 'async',
    'asíncrona': 'async',
    'enrutar': 'route',
    'enrutador': 'router',
    'arreglo': 'array',
    'arreglos': 'arrays',
    'matriz': 'matrix',
    'cadena': 'string',
    'cadenas': 'strings',
    'objeto': 'object',
    'objetos': 'objects',
    'clase': 'class',
    'clases': 'classes',
    'función': 'function',
    'funciones': 'functions',
    'método': 'method',
    'métodos': 'methods',
    'token': 'token',
    'tokens': 'tokens',
    'contenedor': 'container',
    'contenedores': 'containers',
    'despliegue': 'deployment',
    'producción': 'production',
    'desarrollo': 'development',
    'servidor': 'server',
    'cliente': 'client',
    'configuración': 'config',
    'interfaz': 'interface',
    'excepción': 'exception',
    'argumento': 'argument',
    'parámetro': 'parameter',
    'instancia': 'instance',
    'herencia': 'inheritance',

    # Короткие команды и токены
    'booleano': 'boolean',
    'entero': 'integer',
    'nulo': 'null',
    'vacío': 'void',
    'si': 'if',
    'sino': 'else',
    'mientras': 'while',
    'para': 'for',
    'retornar': 'return',
    'devuelve': 'returns',
    'romper': 'break',
    'intentar': 'try',
    'capturar': 'catch',
    'lanzar': 'throw',
    'constante': 'const',
    'var': 'var',
    'let': 'let',
    'igual': 'equal',
    'diferente': 'not equal',
    'mayor': 'greater',
    'menor': 'less',
    'y': 'and',
    'o': 'or',
    'no': 'not',
    'unir': 'join',
    'clon': 'clone',
    'error': 'error',
    'logs': 'logs',
    'api': 'API',
    'pr': 'PR',
}

def translate(text: str) -> str:
    """Заменяет испанский IT-сленг на английские термины."""
    result = text
    # Сортировка по длине важна, чтобы "programación orientada a objetos" 
    # не разбилось на отдельные слова преждевременно.
    for term in sorted(TERMS, key=len, reverse=True):
        pattern = r'(?<!\w)' + re.escape(term) + r'(?!\w)'
        result = re.sub(pattern, TERMS[term], result, flags=re.IGNORECASE)
    return result

if __name__ == "__main__":
    # Тестовый пример, имитирующий типичную речь испанского разраба:
    sample = "Abre el repo, haz pushear a gijab y deploya el contenedor en producción con la base de datos"
    print(translate(sample))
    # Вывод: "Abre el repo, haz push a GitHub y deploy el container en production con la database"