# -*- coding: utf-8 -*-
"""
DE -> EN Wörterbuch für IT- und Entwickler-Slang (Немецкий язык).

Включает Denglisch-глаголы (pushen, gepusht, gedeployt), сложные немецкие 
существительные и частые фонетические искажения немецких STT-движков (reiäkt, tscheison).
"""

import re

TERMS = {
    # 1. Fortgeschrittene Ausdrücke und Konstrukte (Сложные фразы и конструкции)
    'objektorientierte programmierung': 'object-oriented programming',
    'funktionale programmierung': 'functional programming',
    'kommandozeilenoberfläche': 'command line interface',
    'gibt einen boolean zurück': 'returns boolean',
    'gibt ein array zurück': 'returns array',
    'gibt einen string zurück': 'returns string',
    'gibt ein objekt zurück': 'returns object',
    'gibt einen integer zurück': 'returns integer',
    'in der konsole ausgeben': 'console.log',
    'auf der konsole ausgeben': 'console.log',
    'doppelt verkettete liste': 'doubly linked list',
    'einfach verkettete liste': 'singly linked list',
    'regelmäßiger ausdruck': 'regular expression',
    'regulärer ausdruck': 'regular expression',
    'umgebungsvariable': 'environment variable',
    'benutzeroberfläche': 'user interface',
    'aufbrechen von strukturen': 'destructuring',
    'end-to-end-test': 'end-to-end test',
    'integrationstest': 'integration test',
    'funktion höherer ordnung': 'higher-order function',
    'öffentlicher schlüssel': 'private key',
    'privater schlüssel': 'private key',
    'lokaler server': 'localhost',
    'verkettete liste': 'linked list',
    'binärer baum': 'binary tree',
    'quellcode': 'source code',
    'gleitkommazahl': 'float',
    'ganzzahl': 'integer',
    'standardmäßig': 'default',
    'fehlerbehandlung': 'error handling',
    'schleife': 'loop',

    # 2. Denglisch-Verben (Все формы немецких ИТ-глаголов для STT)
    'refactoren': 'refactor',
    'refactort': 'refactor',
    'gerefactort': 'refactored',
    'debuggen': 'debug',
    'debuggt': 'debug',
    'gedebuggt': 'debugged',
    'committen': 'commit',
    'committet': 'commit',
    'gecommittet': 'committed',
    'deployen': 'deploy',
    'deployt': 'deploy',
    'gedeployt': 'deployed',
    'deployend': 'deploying',
    'pushen': 'push',
    'pusht': 'push',
    'gepusht': 'pushed',
    'pushend': 'pushing',
    'pullen': 'pull',
    'pullt': 'pull',
    'gepullt': 'pulled',
    'mergen': 'merge',
    'mergt': 'merge',
    'gemergt': 'merged',
    'builden': 'build',
    'buildet': 'build',
    'gebuildet': 'built',
    'clonen': 'clone',
    'geclont': 'cloned',
    'parsen': 'parse',
    'parst': 'parse',
    'geparst': 'parsed',
    'crashen': 'crash',
    'gecrasht': 'crashed',
    'upgraden': 'upgrade',
    'upgradet': 'upgrade',
    'geupgradet': 'upgraded',
    'einloggen': 'login',
    'ausloggen': 'logout',
    'scrollen': 'scroll',
    'klicken': 'click',
    'geblickt': 'clicked',
    'testen': 'test',
    'getestet': 'tested',
    'resetten': 'reset',
    'geresettet': 'reset',
    'ausführen': 'run',
    'initialisieren': 'initialize',
    'optimieren': 'optimize',

    # 3. Phonetische Verzerrungen / Deutsches STT (Фонетика и немецкий акцент)
    'dschavascript': 'JavaScript',
    'dschavascri': 'JavaScript',
    'yavascrit': 'JavaScript',
    'taipskript': 'TypeScript',
    'taipskri': 'TypeScript',
    'reiäkt': 'React',
    'riäkt': 'React',
    'githap': 'GitHub',
    'githabb': 'GitHub',
    'gitläb': 'GitLab',
    'doker': 'Docker',
    'kuber': 'Kubernetes',
    'kubernetis': 'Kubernetes',
    'tscheison': 'JSON',
    'jason': 'JSON',
    'esquell': 'SQL',
    'es-que-el': 'SQL',
    'graftquell': 'GraphQL',
    'bäckend': 'backend',
    'frontänd': 'frontend',
    'wisual studio': 'Visual Studio',
    'wskooud': 'VS Code',
    'fech': 'fetch',
    'bäkap': 'backup',

    # 4. Nomen und Konzepte (Существительные и концепты)
    'datenbank': 'database',
    'datenbanken': 'databases',
    'schnittstelle': 'interface',
    'schnittstellen': 'interfaces',
    'fehlermeldung': 'error message',
    'anfrage': 'request',
    'antwort': 'response',
    'repository': 'repository',
    'repo': 'repo',
    'repos': 'repos',
    'zweig': 'branch',
    'zweige': 'branches',
    'umgebung': 'environment',
    'datei': 'file',
    'dateien': 'files',
    'ordner': 'folder',
    'verzeichnis': 'directory',
    'bibliothek': 'library',
    'bibliotheken': 'libraries',
    'vererbung': 'inheritance',
    'ausnahme': 'exception',
    'ausnahmen': 'exceptions',
    'argument': 'argument',
    'parameter': 'parameter',
    'instanz': 'instance',
    'objekt': 'object',
    'klasse': 'class',
    'klassen': 'classes',
    'funktion': 'function',
    'funktionen': 'functions',
    'methode': 'method',
    'methoden': 'methods',
    'token': 'token',
    'container': 'container',
    'bereitstellung': 'deployment',
    'produktion': 'production',
    'entwicklung': 'development',
    'server': 'server',
    'client': 'client',
    'konfiguration': 'config',
    'wert': 'value',
    'schlüssel': 'key',
    'zeile': 'row',
    'spalte': 'column',

    # 5. Programmier-Schlüsselwörter (Ключевые слова программирования)
    'boolean': 'boolean',
    'integer': 'integer',
    'float': 'float',
    'string': 'string',
    'array': 'array',
    'null': 'null',
    'wenn': 'if',
    'sonst wenn': 'else if',
    'sonst': 'else',
    'für': 'for',
    'solange': 'while',
    'rückgabe': 'return',
    'zurückgeben': 'return',
    'abbrechen': 'break',
    'fortsetzen': 'continue',
    'versuchen': 'try',
    'fangen': 'catch',
    'werfen': 'throw',
    'konstante': 'const',
    'variable': 'variable',
    'gleich': 'equal',
    'nicht gleich': 'not equal',
    'größer': 'greater',
    'kleiner': 'less',
    'und': 'and',
    'oder': 'or',
    'nicht': 'not',
    'fehler': 'error',
    'protokolle': 'logs',
    'api': 'API',
    'pr': 'PR',
}

def translate(text: str) -> str:
    """Ersetzt deutschen IT-Slang durch englische Begriffe."""
    result = text
    # Sortierung nach Länge verhindert, dass zusammengesetzte Wörter falsch zerlegt werden.
    for term in sorted(TERMS, key=len, reverse=True):
        pattern = r'(?<!\w)' + re.escape(term) + r'(?!\w)'
        result = re.sub(pattern, TERMS[term], result, flags=re.IGNORECASE)
    return result

if __name__ == "__main__":
    # Testbeispiel für Denglisch / deutsches STT:
    sample = "Öffne das reiäkt Projekt, bitte gepusht zu githap und danach auf vercel deployen"
    print(translate(sample))
    # Erwartete Ausgabe: "Öffne das React Projekt, bitte push zu GitHub und danach auf vercel deploy"