"""Russian phonetic -> English tech term replacements."""

# Russian phonetic → English tech term replacements
# Big dictionary of programming terms
TERM_REPLACEMENTS = {

    # ====================
    # RU -> EN переводы
    # ====================

    'возвращает булевое значение': 'returns boolean',
    'возвращает значение': 'returns value',
    'принимает на вход': 'takes',
    'возвращает массив': 'returns array',
    'возвращает строку': 'returns string',
    'возвращает объект': 'returns object',
    'вывести в консоль': 'console.log',
    'возвращает число': 'returns number',
    'больше или равно': 'greater or equal',
    'меньше или равно': 'less or equal',
    'выведи в консоль': 'console.log',
    'и тому подобное': 'etc',
    'экспортировать': 'export',
    'переименовать': 'rename',
    'останавливает': 'stops',
    'перезапустить': 'restart',
    'устанавливает': 'installs',
    'дробное число': 'float',
    'дробные числа': 'floats',
    'импортировать': 'import',
    'обрабатывает': 'handles',
    'неопределено': 'undefined',
    'по умолчанию': 'default',
    'переместить': 'move',
    'перезапусти': 'restart',
    'целое число': 'integer',
    'целые числа': 'integers',
    'для каждого': 'for each',
    'статический': 'static',
    'абстрактный': 'abstract',
    'асинхронный': 'async',
    'асинхронная': 'async',
    'асинхронное': 'async',
    'экспортируй': 'export',
    'тестировать': 'test',
    'протестируй': 'test',
    'и так далее': 'etc',
    'конструктор': 'constructor',
    'копировать': 'copy',
    'переименуй': 'rename',
    'остановить': 'stop',
    'установить': 'install',
    'показывает': 'shows',
    'исправляет': 'fixes',
    'обработать': 'handle',
    'отправляет': 'sends',
    'возвращает': 'returns',
    'логическое': 'boolean',
    'иначе если': 'else if',
    'продолжить': 'continue',
    'защищенный': 'protected',
    'импортируй': 'import',
    'исключение': 'catch',
    'утверждать': 'assert',
    'директория': 'directory',
    'компоненты': 'components',
    'библиотека': 'library',
    'библиотеки': 'libraries',
    'контроллер': 'controller',
    'перемести': 'move',
    'сохранить': 'save',
    'загрузить': 'load',
    'запустить': 'run',
    'запускает': 'runs',
    'обновляет': 'updates',
    'добавляет': 'adds',
    'проверить': 'check',
    'проверяет': 'checks',
    'исправить': 'fix',
    'обработай': 'handle',
    'выполнить': 'execute',
    'выполняет': 'executes',
    'отправить': 'send',
    'присвоить': 'assign',
    'назначить': 'assign',
    'принимает': 'takes',
    'множество': 'set',
    'повторять': 'repeat',
    'равняется': 'equals',
    'разделить': 'divide',
    'публичный': 'public',
    'приватный': 'private',
    'константа': 'const',
    'требовать': 'require',
    'выбросить': 'throw',
    'прочитать': 'read',
    'заголовок': 'header',
    'компонент': 'component',
    'интерфейс': 'interface',
    'скопируй': 'copy',
    'останови': 'stop',
    'обновить': 'update',
    'установи': 'install',
    'добавить': 'add',
    'изменить': 'modify',
    'изменяет': 'modifies',
    'показать': 'show',
    'получить': 'get',
    'получает': 'gets',
    'прервать': 'break',
    'не равно': 'not equal',
    'умножить': 'multiply',
    'финально': 'finally',
    'замокать': 'mock',
    'фикстура': 'fixture',
    'фикстуры': 'fixtures',
    'прочитай': 'read',
    'записать': 'write',
    'эндпоинт': 'endpoint',
    'создать': 'create',
    'создает': 'creates',
    'удалить': 'remove',
    'открыть': 'open',
    'закрыть': 'close',
    'сохрани': 'save',
    'загрузи': 'load',
    'запусти': 'run',
    'проверь': 'check',
    'исправь': 'fix',
    'выполни': 'execute',
    'отправь': 'send',
    'вернуть': 'return',
    'присвой': 'assign',
    'булевое': 'boolean',
    'массивы': 'arrays',
    'объекты': 'objects',
    'словарь': 'dictionary',
    'пустота': 'void',
    'сложить': 'add',
    'вычесть': 'subtract',
    'ожидать': 'await',
    'подожди': 'await',
    'экспорт': 'export',
    'попытка': 'try',
    'бросить': 'throw',
    'мидлвар': 'middleware',
    'функция': 'function',
    'создай': 'create',
    'открой': 'open',
    'закрой': 'close',
    'обнови': 'update',
    'добавь': 'add',
    'измени': 'modify',
    'искать': 'search',
    'покажи': 'show',
    'скрыть': 'hide',
    'решить': 'solve',
    'решает': 'solves',
    'получи': 'get',
    'строка': 'string',
    'строки': 'strings',
    'массив': 'array',
    'список': 'list',
    'списки': 'lists',
    'объект': 'object',
    'кортеж': 'tuple',
    'выбора': 'switch',
    'случай': 'case',
    'больше': 'greater',
    'меньше': 'less',
    'импорт': 'import',
    'запиши': 'write',
    'запрос': 'request',
    'статус': 'status',
    'модуль': 'module',
    'модули': 'modules',
    'пакеты': 'packages',
    'сервис': 'service',
    'функшн': 'function',
    'фанкшн': 'function',
    'методы': 'methods',
    'удали': 'delete',
    'найти': 'find',
    'найди': 'find',
    'скрой': 'hide',
    'верни': 'return',
    'число': 'number',
    'числа': 'numbers',
    'ничто': 'null',
    'иначе': 'else',
    'равно': 'equal',
    'тесты': 'tests',
    'файлы': 'files',
    'папка': 'folder',
    'ответ': 'response',
    'пакет': 'package',
    'метод': 'method',
    'класс': 'class',
    'реши': 'solve',
    'если': 'if',
    'пока': 'while',
    'тест': 'test',
    'файл': 'file',
    'путь': 'path',
    'тело': 'body',
    'логи': 'logs',
    'ищи': 'search',
    'для': 'for',
    'или': 'or',
    'мок': 'mock',
    'код': 'code',
    'лог': 'log',
    'до': 'until',
    'не': 'not',
    'и': 'and',

    # === React / Hooks ===
    'юзстейт': 'useState',
    'юз стейт': 'useState',
    'юзэффект': 'useEffect',
    'юз эффект': 'useEffect',
    'юзконтекст': 'useContext',
    'юз контекст': 'useContext',
    'юзреф': 'useRef',
    'юз реф': 'useRef',
    'юзмемо': 'useMemo',
    'юз мемо': 'useMemo',
    'юзколбэк': 'useCallback',
    'юз колбэк': 'useCallback',
    'юзредьюсер': 'useReducer',
    'юз редьюсер': 'useReducer',
    'юзлэйаут эффект': 'useLayoutEffect',
    'юзимперативхендл': 'useImperativeHandle',
    'пропс': 'props',
    'пропсы': 'props',
    'стейт': 'state',
    'сетстейт': 'setState',
    'компонент': 'component',
    'компоненты': 'components',
    'хук': 'hook',
    'хуки': 'hooks',
    'контекст': 'context',
    'провайдер': 'provider',
    'консьюмер': 'consumer',
    'редьюсер': 'reducer',
    'экшен': 'action',
    'экшн': 'action',
    'диспатч': 'dispatch',
    'редакс': 'Redux',
    'мобэкс': 'MobX',
    'зустанд': 'Zustand',
    'джотай': 'Jotai',
    'рекойл': 'Recoil',
    
    # === Languages / Frameworks ===
    'джаваскрипт': 'JavaScript',
    'джава скрипт': 'JavaScript',
    'джс': 'JS',
    'тайпскрипт': 'TypeScript',
    'тайп скрипт': 'TypeScript',
    'тс': 'TS',
    'питон': 'Python',
    'пайтон': 'Python',
    'пай': 'py',
    'джава': 'Java',
    'котлин': 'Kotlin',
    'свифт': 'Swift',
    'обджектив си': 'Objective-C',
    'сишарп': 'C#',
    'си шарп': 'C#',
    'сиплюсплюс': 'C++',
    'си плюс плюс': 'C++',
    'гоу': 'Go',
    'голанг': 'Golang',
    'раст': 'Rust',
    'руби': 'Ruby',
    'пхп': 'PHP',
    'пиэйчпи': 'PHP',
    'перл': 'Perl',
    'скала': 'Scala',
    'эликсир': 'Elixir',
    'кложур': 'Clojure',
    'хаскелл': 'Haskell',
    'эрланг': 'Erlang',
    'люа': 'Lua',
    'дарт': 'Dart',
    'зиг': 'Zig',
    
    # === Frontend Frameworks ===
    'реакт': 'React',
    'риэкт': 'React',
    'вью': 'Vue',
    'вьюджс': 'Vue.js',
    'ангуляр': 'Angular',
    'свелт': 'Svelte',
    'свелткит': 'SvelteKit',
    'некст': 'Next.js',
    'некстджс': 'Next.js',
    'нукст': 'Nuxt',
    'нукстджс': 'Nuxt.js',
    'гэтсби': 'Gatsby',
    'ремикс': 'Remix',
    'астро': 'Astro',
    'солид': 'Solid',
    'солиджс': 'SolidJS',
    'квик': 'Qwik',
    'преакт': 'Preact',
    'алпайн': 'Alpine.js',
    'эмбер': 'Ember',
    'бэкбон': 'Backbone',
    'джейквери': 'jQuery',
    'джи квери': 'jQuery',
    
    # === Backend Frameworks ===
    'ноджс': 'Node.js',
    'нод': 'Node',
    'экспресс': 'Express',
    'экспрессджс': 'Express.js',
    'фастифай': 'Fastify',
    'коа': 'Koa',
    'нест': 'Nest',
    'нестджс': 'NestJS',
    'джанго': 'Django',
    'фласк': 'Flask',
    'фастапи': 'FastAPI',
    'фаст апи': 'FastAPI',
    'эйоник': 'aiohttp',
    'торнадо': 'Tornado',
    'рейлс': 'Rails',
    'руби он рейлс': 'Ruby on Rails',
    'ларавел': 'Laravel',
    'симфони': 'Symfony',
    'спринг': 'Spring',
    'спринг бут': 'Spring Boot',
    'джин': 'Gin',
    'эхо': 'Echo',
    'файбер': 'Fiber',
    'актикс': 'Actix',
    'рокет': 'Rocket',
    'флаттер': 'Flutter',
    'реакт нейтив': 'React Native',
    'электрон': 'Electron',
    'таури': 'Tauri',
    
    # === CSS / Styling ===
    'цсс': 'CSS',
    'сиэсэс': 'CSS',
    'сасс': 'Sass',
    'скссс': 'SCSS',
    'лесс': 'Less',
    'стайлус': 'Stylus',
    'тейлвинд': 'Tailwind',
    'тэйлвинд': 'Tailwind',
    'бутстрап': 'Bootstrap',
    'материал юай': 'Material UI',
    'чакра': 'Chakra',
    'чакра юай': 'Chakra UI',
    'энт дизайн': 'Ant Design',
    'стайлд компонентс': 'styled-components',
    'эмоушн': 'Emotion',
    'флексбокс': 'Flexbox',
    'флекс': 'flex',
    'грид': 'grid',
    'медиа квери': 'media query',
    
    # === Build Tools / Bundlers ===
    'вебпак': 'Webpack',
    'вайт': 'Vite',
    'роллап': 'Rollup',
    'парсел': 'Parcel',
    'есбилд': 'esbuild',
    'свц': 'SWC',
    'бабель': 'Babel',
    'бейбл': 'Babel',
    'тёрбо': 'Turbo',
    'турбопак': 'Turbopack',
    'турборепо': 'Turborepo',
    'лёрна': 'Lerna',
    'нх': 'Nx',
    
    # === Package Managers ===
    'нпм': 'npm',
    'энпиэм': 'npm',
    'ярн': 'yarn',
    'пнпм': 'pnpm',
    'бан': 'bun',
    'пип': 'pip',
    'пипенв': 'pipenv',
    'поэтри': 'poetry',
    'карго': 'cargo',
    'композер': 'composer',
    'мавен': 'Maven',
    'грэдл': 'Gradle',
    'кокоаподс': 'CocoaPods',
    'брю': 'brew',
    'хоумбрю': 'Homebrew',
    'чоко': 'choco',
    'чоколати': 'Chocolatey',
    
    # === Testing ===
    'джест': 'Jest',
    'витест': 'Vitest',
    'мока': 'Mocha',
    'чай': 'Chai',
    'жасмин': 'Jasmine',
    'карма': 'Karma',
    'сайпресс': 'Cypress',
    'плейврайт': 'Playwright',
    'паппетир': 'Puppeteer',
    'селениум': 'Selenium',
    'юнит тест': 'unit test',
    'юнит тесты': 'unit tests',
    'интеграционный тест': 'integration test',
    'е ту е': 'e2e',
    'иту|и': 'e2e',
    'энд ту энд': 'end-to-end',
    'мок': 'mock',
    'моки': 'mocks',
    'стаб': 'stub',
    'спай': 'spy',
    'фикстура': 'fixture',
    'ассерт': 'assert',
    'эксепт': 'expect',
    'тест кейс': 'test case',
    'тест сьют': 'test suite',
    'ковередж': 'coverage',
    'покрытие': 'coverage',
    
    # === Git / Version Control ===
    'гит': 'git',
    'гитхаб': 'GitHub',
    'гитлаб': 'GitLab',
    'битбакет': 'Bitbucket',
    'коммит': 'commit',
    'коммиты': 'commits',
    'пуш': 'push',
    'пушить': 'push',
    'пул': 'pull',
    'пулить': 'pull',
    'фетч': 'fetch',
    'клон': 'clone',
    'клонировать': 'clone',
    'пулл реквест': 'pull request',
    'пул реквест': 'pull request',
    'пи ар': 'PR',
    'мёрдж': 'merge',
    'мердж': 'merge',
    'мёрджить': 'merge',
    'бранч': 'branch',
    'бранчи': 'branches',
    'ветка': 'branch',
    'ветки': 'branches',
    'ребейз': 'rebase',
    'черри пик': 'cherry-pick',
    'черрипик': 'cherry-pick',
    'сташ': 'stash',
    'стэш': 'stash',
    'чекаут': 'checkout',
    'чек аут': 'checkout',
    'ресет': 'reset',
    'риверт': 'revert',
    'дифф': 'diff',
    'блейм': 'blame',
    'тег': 'tag',
    'теги': 'tags',
    'ориджин': 'origin',
    'апстрим': 'upstream',
    'ремоут': 'remote',
    'хед': 'HEAD',
    'мастер': 'master',
    'мейн': 'main',
    'девелоп': 'develop',
    'фича': 'feature',
    'хотфикс': 'hotfix',
    'релиз': 'release',
    'гитигнор': '.gitignore',
    
    # === DevOps / Infrastructure ===
    'докер': 'Docker',
    'докерфайл': 'Dockerfile',
    'докер компоуз': 'docker-compose',
    'контейнер': 'container',
    'контейнеры': 'containers',
    'имидж': 'image',
    'имейдж': 'image',
    'кубернетес': 'Kubernetes',
    'кубер': 'Kubernetes',
    'кейт эйт эс': 'K8s',
    'кубернетис': 'Kubernetes',
    'хелм': 'Helm',
    'истио': 'Istio',
    'терраформ': 'Terraform',
    'ансибл': 'Ansible',
    'паппет': 'Puppet',
    'шеф': 'Chef',
    'вагрант': 'Vagrant',
    'дженкинс': 'Jenkins',
    'гитхаб экшенс': 'GitHub Actions',
    'гитлаб сиай': 'GitLab CI',
    'сиай сиди': 'CI/CD',
    'си ай': 'CI',
    'си ди': 'CD',
    'пайплайн': 'pipeline',
    'деплой': 'deploy',
    'деплоймент': 'deployment',
    'продакшен': 'production',
    'продакшн': 'production',
    'прод': 'prod',
    'стейджинг': 'staging',
    'стейдж': 'stage',
    'дев': 'dev',
    'локал': 'local',
    'энвайронмент': 'environment',
    'энв': 'env',
    'конфиг': 'config',
    'конфигурация': 'configuration',
    
    # === Cloud Providers ===
    'авс': 'AWS',
    'эйдаблюэс': 'AWS',
    'амазон': 'Amazon',
    'эй даблю эс': 'AWS',
    'гугл клауд': 'Google Cloud',
    'джисипи': 'GCP',
    'азур': 'Azure',
    'эйжур': 'Azure',
    'майкрософт азур': 'Microsoft Azure',
    'дигитал оушен': 'DigitalOcean',
    'херроку': 'Heroku',
    'хероку': 'Heroku',
    'верцель': 'Vercel',
    'версель': 'Vercel',
    'нетлифай': 'Netlify',
    'клаудфлер': 'Cloudflare',
    'файрбейз': 'Firebase',
    'фаербейс': 'Firebase',
    'сюпабейз': 'Supabase',
    'супабейс': 'Supabase',
    'планетскейл': 'PlanetScale',
    'рейлвей': 'Railway',
    'флай ио': 'Fly.io',
    
    # === Databases ===
    'постгрес': 'PostgreSQL',
    'постгрескюэл': 'PostgreSQL',
    'постгря': 'Postgres',
    'майскюэл': 'MySQL',
    'мускул': 'MySQL',
    'маскюэл': 'MySQL',
    'скюлайт': 'SQLite',
    'скюэлайт': 'SQLite',
    'монго': 'MongoDB',
    'монгодиби': 'MongoDB',
    'редис': 'Redis',
    'мемкэшд': 'Memcached',
    'эластиксёрч': 'Elasticsearch',
    'эластик': 'Elastic',
    'кассандра': 'Cassandra',
    'динамодиби': 'DynamoDB',
    'коучдиби': 'CouchDB',
    'нео фор джей': 'Neo4j',
    'скюэл': 'SQL',
    'эскуэль': 'SQL',
    'ноускюэл': 'NoSQL',
    'орм': 'ORM',
    'призма': 'Prisma',
    'секвелайз': 'Sequelize',
    'тайпорм': 'TypeORM',
    'дризл': 'Drizzle',
    'алембик': 'Alembic',
    'миграция': 'migration',
    'миграции': 'migrations',
    'сидинг': 'seeding',
    'сид': 'seed',
    'скима': 'schema',
    'схема': 'schema',
    'таблица': 'table',
    'колонка': 'column',
    'индекс': 'index',
    'квери': 'query',
    'кверя': 'query',
    'джойн': 'join',
    'лефт джойн': 'LEFT JOIN',
    'иннер джойн': 'INNER JOIN',
    'веар': 'WHERE',
    'ордер бай': 'ORDER BY',
    'груп бай': 'GROUP BY',
    'хэвинг': 'HAVING',
    'лимит': 'LIMIT',
    'оффсет': 'OFFSET',
    'транзакция': 'transaction',
    
    # === APIs / Protocols ===
    'эй пи ай': 'API',
    'апи': 'API',
    'рест': 'REST',
    'рестфул': 'RESTful',
    'графкюэл': 'GraphQL',
    'граф кюэл': 'GraphQL',
    'джейсон': 'JSON',
    'джсон': 'JSON',
    'иксэмэл': 'XML',
    'хмл': 'XML',
    'эйчтиэмэл': 'HTML',
    'хтмл': 'HTML',
    'ямл': 'YAML',
    'йамл': 'YAML',
    'томл': 'TOML',
    'эйчтитипи': 'HTTP',
    'хттп': 'HTTP',
    'эйчтитипиэс': 'HTTPS',
    'хттпс': 'HTTPS',
    'вебсокет': 'WebSocket',
    'веб сокет': 'WebSocket',
    'сокет': 'socket',
    'сокеты': 'sockets',
    'сокет ио': 'Socket.io',
    'грпц': 'gRPC',
    'джиарписи': 'gRPC',
    'тиарписи': 'tRPC',
    'оаус': 'OAuth',
    'о аус': 'OAuth',
    'джейдаблютэ': 'JWT',
    'джот': 'JWT',
    'токен': 'token',
    'токены': 'tokens',
    'эндпоинт': 'endpoint',
    'эндпоинты': 'endpoints',
    'роут': 'route',
    'роуты': 'routes',
    'роутер': 'router',
    'роутинг': 'routing',
    'мидлвер': 'middleware',
    'мидлвэр': 'middleware',
    'хедер': 'header',
    'хедеры': 'headers',
    'хэдер': 'header',
    'бади': 'body',
    'боди': 'body',
    'пэйлоад': 'payload',
    'пейлоад': 'payload',
    'респонс': 'response',
    'респонсы': 'responses',
    'реквест': 'request',
    'реквесты': 'requests',
    'статус код': 'status code',
    'корс': 'CORS',
    'вебхук': 'webhook',
    'вебхуки': 'webhooks',
    
    # === AI / ML ===
    'девин': 'Devin',
    'клод': 'Claude',
    'джипити': 'GPT',
    'чатджипити': 'ChatGPT',
    'чат джипити': 'ChatGPT',
    'опенэйай': 'OpenAI',
    'опен эй ай': 'OpenAI',
    'антропик': 'Anthropic',
    'копайлот': 'Copilot',
    'коупайлот': 'Copilot',
    'джемини': 'Gemini',
    'лама': 'LLaMA',
    'мистраль': 'Mistral',
    'промт': 'prompt',
    'промпт': 'prompt',
    'промты': 'prompts',
    'промпты': 'prompts',
    'эмбеддинг': 'embedding',
    'эмбеддинги': 'embeddings',
    'файнтюнинг': 'fine-tuning',
    'файн тюнинг': 'fine-tuning',
    'инференс': 'inference',
    'модел': 'model',
    'модель': 'model',
    'нейросеть': 'neural network',
    'трансформер': 'transformer',
    'аттеншен': 'attention',
    'лангчейн': 'LangChain',
    'ланг чейн': 'LangChain',
    'лламаиндекс': 'LlamaIndex',
    'пайторч': 'PyTorch',
    'тензорфлоу': 'TensorFlow',
    'керас': 'Keras',
    'сайкитлёрн': 'scikit-learn',
    'хаггингфейс': 'Hugging Face',
    
    # === JavaScript/TypeScript Keywords ===
    'функция': 'function',
    'функшн': 'function',
    'фанкшн': 'function',
    'класс': 'class',
    'классы': 'classes',
    'метод': 'method',
    'методы': 'methods',
    'модуль': 'module',
    'модули': 'modules',
    'пакет': 'package',
    'пакеты': 'packages',
    'импорт': 'import',
    'импортировать': 'import',
    'экспорт': 'export',
    'экспортировать': 'export',
    'дефолт': 'default',
    'дифолт': 'default',
    'конст': 'const',
    'константа': 'const',
    'лет': 'let',
    'вар': 'var',
    'иф': 'if',
    'элс': 'else',
    'элс иф': 'else if',
    'фор': 'for',
    'форич': 'forEach',
    'фор ич': 'forEach',
    'вайл': 'while',
    'ду вайл': 'do while',
    'свитч': 'switch',
    'кейс': 'case',
    'брейк': 'break',
    'континью': 'continue',
    'ретурн': 'return',
    'риторн': 'return',
    'ретёрн': 'return',
    'трай': 'try',
    'кэтч': 'catch',
    'файналли': 'finally',
    'троу': 'throw',
    'сроу': 'throw',
    'нью': 'new',
    'дис': 'this',
    'зис': 'this',
    'супер': 'super',
    'экстендс': 'extends',
    'имплементс': 'implements',
    'статик': 'static',
    'паблик': 'public',
    'прайват': 'private',
    'протектед': 'protected',
    'эсинк': 'async',
    'эсюнк': 'async',
    'эвейт': 'await',
    'авэйт': 'await',
    'йилд': 'yield',
    'йелд': 'yield',
    'промис': 'Promise',
    'промисы': 'promises',
    'зен': 'then',
    'эррор': 'error',
    'эксепшн': 'exception',
    'эксепшен': 'exception',
    
    # === Types ===
    'тайп': 'type',
    'тайпы': 'types',
    'интерфейс': 'interface',
    'интерфейсы': 'interfaces',
    'стринг': 'string',
    'стринги': 'strings',
    'намбер': 'number',
    'намберы': 'numbers',
    'буллеан': 'boolean',
    'булеан': 'boolean',
    'бул': 'bool',
    'булл': 'boolean',
    'эррей': 'array',
    'эррэй': 'array',
    'массив': 'array',
    'обджект': 'object',
    'объект': 'object',
    'нулл': 'null',
    'налл': 'null',
    'андефайнд': 'undefined',
    'войд': 'void',
    'эни': 'any',
    'анноун': 'unknown',
    'невер': 'never',
    'тупл': 'tuple',
    'тюпл': 'tuple',
    'кортеж': 'tuple',
    'энам': 'enum',
    'инам': 'enum',
    'юнион': 'union',
    'дженерик': 'generic',
    'дженерики': 'generics',
    'тайпоф': 'typeof',
    'тайп оф': 'typeof',
    'кейоф': 'keyof',
    'кей оф': 'keyof',
    'ридонли': 'readonly',
    'рид онли': 'readonly',
    'партиал': 'Partial',
    'рекорд': 'Record',
    'пик': 'Pick',
    'омит': 'Omit',
    'эксклуд': 'Exclude',
    'экстракт': 'Extract',
    'нон наллабл': 'NonNullable',
    'ретурн тайп': 'ReturnType',
    
    # === Common Programming Concepts ===
    'вариабл': 'variable',
    'переменная': 'variable',
    'переменные': 'variables',
    'аргумент': 'argument',
    'аргументы': 'arguments',
    'параметр': 'parameter',
    'параметры': 'parameters',
    'колбэк': 'callback',
    'колбек': 'callback',
    'хендлер': 'handler',
    'хэндлер': 'handler',
    'листенер': 'listener',
    'ивент': 'event',
    'евент': 'event',
    'ивенты': 'events',
    'эмит': 'emit',
    'эмитить': 'emit',
    'сабскрайб': 'subscribe',
    'ансабскрайб': 'unsubscribe',
    'обсёрвер': 'observer',
    'обсервер': 'observer',
    'паттерн': 'pattern',
    'паттерны': 'patterns',
    'алгоритм': 'algorithm',
    'рекурсия': 'recursion',
    'рекурсивный': 'recursive',
    'итерация': 'iteration',
    'итератор': 'iterator',
    'итерировать': 'iterate',
    'луп': 'loop',
    'цикл': 'loop',
    'циклы': 'loops',
    'условие': 'condition',
    'условия': 'conditions',
    'кондишн': 'condition',
    'тернарный': 'ternary',
    'оператор': 'operator',
    'операторы': 'operators',
    'инкремент': 'increment',
    'декремент': 'decrement',
    'конкатенация': 'concatenation',
    'интерполяция': 'interpolation',
    'деструктуризация': 'destructuring',
    'спред': 'spread',
    'дефолт вэлью': 'default value',
    
    # === Data Structures ===
    'структура': 'structure',
    'структуры': 'structures',
    'стек': 'stack',
    'очередь': 'queue',
    'кью': 'queue',
    'дек': 'deque',
    'лист': 'list',
    'листы': 'lists',
    'линкд лист': 'linked list',
    'связный список': 'linked list',
    'три': 'tree',
    'дерево': 'tree',
    'бинарное дерево': 'binary tree',
    'бинари три': 'binary tree',
    'граф': 'graph',
    'хэш': 'hash',
    'хеш': 'hash',
    'хэшмэп': 'hashmap',
    'хешмап': 'hashmap',
    'сет': 'set',
    'мап': 'map',
    'мапа': 'map',
    'мэп': 'map',
    'дикт': 'dict',
    'словарь': 'dictionary',
    'нода': 'node',
    'ноды': 'nodes',
    'эдж': 'edge',
    'вертекс': 'vertex',
    'рут': 'root',
    'корень': 'root',
    'лиф': 'leaf',
    'парент': 'parent',
    'чайлд': 'child',
    'чилдрен': 'children',
    'сиблинг': 'sibling',
    
    # === OOP ===
    'ооп': 'OOP',
    'о о п': 'OOP',
    'объектно ориентированный': 'object-oriented',
    'наследование': 'inheritance',
    'инхеританс': 'inheritance',
    'полиморфизм': 'polymorphism',
    'инкапсуляция': 'encapsulation',
    'абстракция': 'abstraction',
    'абстрактный': 'abstract',
    'конструктор': 'constructor',
    'деструктор': 'destructor',
    'инстанс': 'instance',
    'инстансы': 'instances',
    'экземпляр': 'instance',
    'объекты': 'objects',
    'проперти': 'property',
    'пропертис': 'properties',
    'геттер': 'getter',
    'сеттер': 'setter',
    'аксессор': 'accessor',
    'мутатор': 'mutator',
    'оверрайд': 'override',
    'оверлоад': 'overload',
    'перегрузка': 'overload',
    'переопределение': 'override',
    
    # === Functional Programming ===
    'эфпи': 'FP',
    'функциональный': 'functional',
    'чистая функция': 'pure function',
    'пьюр фанкшн': 'pure function',
    'иммутабл': 'immutable',
    'иммьютабл': 'immutable',
    'мутабл': 'mutable',
    'мьютабл': 'mutable',
    'сайд эффект': 'side effect',
    'хайер ордер': 'higher order',
    'хоф': 'HOF',
    'карринг': 'currying',
    'композиция': 'composition',
    'пайп': 'pipe',
    'фильтер': 'filter',
    'редьюс': 'reduce',
    'фолд': 'fold',
    'флэтмэп': 'flatMap',
    'флэт': 'flat',
    'фаинд': 'find',
    'файнд': 'find',
    'сам': 'some',
    'эври': 'every',
    'инклудс': 'includes',
    'индексоф': 'indexOf',
    'сорт': 'sort',
    'сортировка': 'sort',
    'реверс': 'reverse',
    'слайс': 'slice',
    'сплайс': 'splice',
    'конкат': 'concat',
    'сплит': 'split',
    'трим': 'trim',
    'сабстринг': 'substring',
    'репсейс': 'replace',
    'реплейс': 'replace',
    'матч': 'match',
    'тест': 'test',
    'серч': 'search',
    
    # === DOM / Browser ===
    'дом': 'DOM',
    'ди оу эм': 'DOM',
    'документ': 'document',
    'виндоу': 'window',
    'элемент': 'element',
    'элементы': 'elements',
    'квери селектор': 'querySelector',
    'гет элемент бай айди': 'getElementById',
    'гет элементс бай класс': 'getElementsByClassName',
    'криейт элемент': 'createElement',
    'аппенд': 'append',
    'аппенд чайлд': 'appendChild',
    'ремув': 'remove',
    'инсерт': 'insert',
    'иннер эйчтиэмэл': 'innerHTML',
    'аутер эйчтиэмэл': 'outerHTML',
    'текст контент': 'textContent',
    'атрибут': 'attribute',
    'атрибуты': 'attributes',
    'сет атрибут': 'setAttribute',
    'гет атрибут': 'getAttribute',
    'класслист': 'classList',
    'класс лист': 'classList',
    'стайл': 'style',
    'стайлы': 'styles',
    'эвент листенер': 'event listener',
    'эдд эвент листенер': 'addEventListener',
    'клик': 'click',
    'сабмит': 'submit',
    'чейндж': 'change',
    'инпут': 'input',
    'фокус': 'focus',
    'блюр': 'blur',
    'скролл': 'scroll',
    'ресайз': 'resize',
    'лоад': 'load',
    'анлоад': 'unload',
    'маунт': 'mount',
    'анмаунт': 'unmount',
    'рендер': 'render',
    'рендеринг': 'rendering',
    'ререндер': 'rerender',
    'гидрейшн': 'hydration',
    'гидратация': 'hydration',
    
    # === Debug / Console ===
    'консоль': 'console',
    'консоль лог': 'console.log',
    'лог': 'log',
    'логи': 'logs',
    'логгер': 'logger',
    'логгинг': 'logging',
    'дебаг': 'debug',
    'дебаггер': 'debugger',
    'дебаггинг': 'debugging',
    'отладка': 'debugging',
    'брейкпоинт': 'breakpoint',
    'брейк поинт': 'breakpoint',
    'точка останова': 'breakpoint',
    'стектрейс': 'stacktrace',
    'стэк трейс': 'stack trace',
    'эрроры': 'errors',
    'ворнинг': 'warning',
    'ворнинги': 'warnings',
    'варнинг': 'warning',
    'инфо': 'info',
    'трейс': 'trace',
    'ассершн': 'assertion',
    
    # === Files / Paths ===
    'файл': 'file',
    'файлы': 'files',
    'директория': 'directory',
    'директории': 'directories',
    'фолдер': 'folder',
    'папка': 'folder',
    'пас': 'path',
    'паф': 'path',
    'путь': 'path',
    'руут': 'root',
    'базнейм': 'basename',
    'дирнейм': 'dirname',
    'экстеншен': 'extension',
    'расширение': 'extension',
    'ридфайл': 'readFile',
    'райтфайл': 'writeFile',
    'эппендфайл': 'appendFile',
    'анлинк': 'unlink',
    'мкдир': 'mkdir',
    'рмдир': 'rmdir',
    'ридир': 'readdir',
    'стат': 'stat',
    'эксистс': 'exists',
    'рид': 'read',
    'райт': 'write',
    'читать': 'read',
    'писать': 'write',
    'создать': 'create',
    'удалить': 'delete',
    'копировать': 'copy',
    'переместить': 'move',
    'переименовать': 'rename',
    'стрим': 'stream',
    'стримы': 'streams',
    'буфер': 'buffer',
    'буферы': 'buffers',
    
    # === Security ===
    'секьюрити': 'security',
    'безопасность': 'security',
    'аутентификация': 'authentication',
    'аусентикейшн': 'authentication',
    'авторизация': 'authorization',
    'осоризейшн': 'authorization',
    'логин': 'login',
    'логаут': 'logout',
    'войти': 'login',
    'выйти': 'logout',
    'сайн ин': 'sign in',
    'сайн ап': 'sign up',
    'сайн аут': 'sign out',
    'пассворд': 'password',
    'пароль': 'password',
    'хэшировать': 'hash',
    'солт': 'salt',
    'соль': 'salt',
    'энкрипт': 'encrypt',
    'дикрипт': 'decrypt',
    'шифровать': 'encrypt',
    'расшифровать': 'decrypt',
    'сертификат': 'certificate',
    'серт': 'cert',
    'ключ': 'key',
    'приватный ключ': 'private key',
    'публичный ключ': 'public key',
    'сикрет': 'secret',
    'секрет': 'secret',
    'креденшалс': 'credentials',
    'кредс': 'creds',
    'ксс': 'XSS',
    'иксэсэс': 'XSS',
    'ксрф': 'CSRF',
    'инджекшн': 'injection',
    'эскейп': 'escape',
    'санитайз': 'sanitize',
    'валидейт': 'validate',
    'валидация': 'validation',
    
    # === Performance ===
    'перформанс': 'performance',
    'производительность': 'performance',
    'оптимизация': 'optimization',
    'оптимайз': 'optimize',
    'кэш': 'cache',
    'кеш': 'cache',
    'кэширование': 'caching',
    'мемоизация': 'memoization',
    'мемоайз': 'memoize',
    'лейзи': 'lazy',
    'лэйзи': 'lazy',
    'лейзи лоадинг': 'lazy loading',
    'код сплиттинг': 'code splitting',
    'трии шейкинг': 'tree shaking',
    'бандл': 'bundle',
    'бандлинг': 'bundling',
    'минификация': 'minification',
    'минифай': 'minify',
    'компрессия': 'compression',
    'гзип': 'gzip',
    'профайлинг': 'profiling',
    'профайлер': 'profiler',
    'бенчмарк': 'benchmark',
    'метрика': 'metric',
    'метрики': 'metrics',
    'латенси': 'latency',
    'латентность': 'latency',
    'сруупут': 'throughput',
    'пропускная способность': 'throughput',
    
    # === Misc Tools ===
    'вокс': 'lazy_comments',
    'войс': 'voice',
    'терминал': 'terminal',
    'шелл': 'shell',
    'баш': 'bash',
    'зш': 'zsh',
    'павершелл': 'PowerShell',
    'пауэршелл': 'PowerShell',
    'cmd': 'cmd',
    'коммандлайн': 'command line',
    'сиэлай': 'CLI',
    'сли': 'CLI',
    'юай': 'UI',
    'ю ай': 'UI',
    'юэкс': 'UX',
    'юзер интерфейс': 'user interface',
    'гуи': 'GUI',
    'гюи': 'GUI',
    'ай ди и': 'IDE',
    'вскод': 'VS Code',
    'ви эс код': 'VS Code',
    'вижуал студио': 'Visual Studio',
    'интеллиджей': 'IntelliJ',
    'вебшторм': 'WebStorm',
    'пайчарм': 'PyCharm',
    'атом': 'Atom',
    'саблайм': 'Sublime',
    'вим': 'Vim',
    'неовим': 'Neovim',
    'имакс': 'Emacs',
    'нано': 'nano',
    'линтер': 'linter',
    'линт': 'lint',
    'линтинг': 'linting',
    'еслинт': 'ESLint',
    'преттиер': 'Prettier',
    'форматтер': 'formatter',
    'форматирование': 'formatting',
    'сниппет': 'snippet',
    'сниппеты': 'snippets',
    'автокомплит': 'autocomplete',
    'интеллисенс': 'IntelliSense',
    'рефакторинг': 'refactoring',
    'рефактор': 'refactor',
    
    # === Common English words (phonetic) ===
    # Clipboard operations
    'паст': 'paste',
    'пэйст': 'paste',
    'пейст': 'paste',
    'копи': 'copy',
    'копия': 'copy',
    'кат': 'cut',
    'андо': 'undo',
    'анду': 'undo',
    'редо': 'redo',
    'риду': 'redo',
    
    # File operations
    'сейв': 'save',
    'сэйв': 'save',
    'лоуд': 'load',
    'опен': 'open',
    'оупен': 'open',
    'клоуз': 'close',
    'клоз': 'close',
    'ньюс': 'news',
    'криейт': 'create',
    'делит': 'delete',
    'мув': 'move',
    
    # Actions
    'ран': 'run',
    'раннинг': 'running',
    'стоп': 'stop',
    'старт': 'start',
    'рестарт': 'restart',
    'клир': 'clear',
    'клиа': 'clear',
    'гет': 'get',
    'пут': 'put',
    'пост': 'post',
    'патч': 'patch',
    'сенд': 'send',
    'ресив': 'receive',
    'апдейт': 'update',
    'апгрейд': 'upgrade',
    'даунгрейд': 'downgrade',
    'инсталл': 'install',
    'анинсталл': 'uninstall',
    'энейбл': 'enable',
    'дизейбл': 'disable',
    'актив': 'active',
    'инактив': 'inactive',
    'экспанд': 'expand',
    'коллапс': 'collapse',
    'шоу': 'show',
    'хайд': 'hide',
    'хидден': 'hidden',
    'визибл': 'visible',
    
    # Common adjectives
    'олд': 'old',
    'бэд': 'bad',
    'гуд': 'good',
    'биг': 'big',
    'смолл': 'small',
    'фаст': 'fast',
    'слоу': 'slow',
    'хард': 'hard',
    'софт': 'soft',
    'лонг': 'long',
    'шорт': 'short',
    'хай': 'high',
    'лоу': 'low',
    'фулл': 'full',
    'эмпти': 'empty',
    'файнал': 'final',
    'ферст': 'first',
    'ласт': 'last',
    'прев': 'prev',
    'превиус': 'previous',
    'каррент': 'current',
    'кастом': 'custom',
    'симпл': 'simple',
    'комплекс': 'complex',
    'бэйсик': 'basic',
    'эдванс': 'advanced',
    'эдвансд': 'advanced',
    
    # Common nouns
    'юзер': 'user',
    'юзеры': 'users',
    'админ': 'admin',
    'гест': 'guest',
    'хост': 'host',
    'хоум': 'home',
    'пейдж': 'page',
    'пэйдж': 'page',
    'сайт': 'site',
    'линк': 'link',
    'линки': 'links',
    'урл': 'URL',
    'ю ар эл': 'URL',
    'имейл': 'email',
    'мейл': 'mail',
    'месседж': 'message',
    'мессадж': 'message',
    'мессейдж': 'message',
    'чат': 'chat',
    'коммент': 'comment',
    'комментс': 'comments',
    'лайк': 'like',
    'шер': 'share',
    'шэр': 'share',
    'вьюс': 'views',
    'дэшборд': 'dashboard',
    'дашборд': 'dashboard',
    'виджет': 'widget',
    'модал': 'modal',
    'попап': 'popup',
    'поп ап': 'popup',
    'тултип': 'tooltip',
    'тул тип': 'tooltip',
    'дропдаун': 'dropdown',
    'дроп даун': 'dropdown',
    'сайдбар': 'sidebar',
    'сайд бар': 'sidebar',
    'футер': 'footer',
    'контент': 'content',
    'враппер': 'wrapper',
    'врэппер': 'wrapper',
    'айтем': 'item',
    'айтемс': 'items',
    'тейбл': 'table',
    'ров': 'row',
    'роу': 'row',
    'колум': 'column',
    'колумн': 'column',
    'селл': 'cell',
    'форм': 'form',
    'формы': 'forms',
    'филд': 'field',
    'филды': 'fields',
    'лейбл': 'label',
    'лэйбл': 'label',
    'плейсхолдер': 'placeholder',
    'баттон': 'button',
    'батн': 'button',
    'кнопка': 'button',
    'чекбокс': 'checkbox',
    'радио': 'radio',
    'селект': 'select',
    'оптион': 'option',
    'опшн': 'option',
    'вэлью': 'value',
    'велью': 'value',
    'валуе': 'value',
    'кей': 'key',
    'айди': 'id',
    'ай ди': 'id',
    'нейм': 'name',
    'тайтл': 'title',
    'дескрипшн': 'description',
    'дескрипшен': 'description',
    'текст': 'text',
    'пикча': 'picture',
    'иконка': 'icon',
    'айкон': 'icon',
    'аватар': 'avatar',
    'бэкграунд': 'background',
    'бордер': 'border',
    'марджин': 'margin',
    'маргин': 'margin',
    'паддинг': 'padding',
    'пэддинг': 'padding',
    'сайз': 'size',
    'сизе': 'size',
    'видс': 'width',
    'вайдс': 'width',
    'хайт': 'height',
    'хэйт': 'height',
    'колор': 'color',
    'колер': 'color',
    
    # Time-related
    'дэйт': 'date',
    'дейт': 'date',
    'тайм': 'time',
    'таймстэмп': 'timestamp',
    'дэдлайн': 'deadline',
    'дедлайн': 'deadline',
    'таймаут': 'timeout',
    'тайм аут': 'timeout',
    'интервал': 'interval',
    'делэй': 'delay',
    'дилэй': 'delay',
    
    # Status
    'саксес': 'success',
    'саксесс': 'success',
    'фейл': 'fail',
    'фэйл': 'fail',
    'фейлд': 'failed',
    'пендинг': 'pending',
    'прогресс': 'progress',
    'комплит': 'complete',
    'комплитед': 'completed',
    'реди': 'ready',
    'рэди': 'ready',
    'лоадинг': 'loading',
    'лоудинг': 'loading',
    'процессинг': 'processing',
    'вэйтинг': 'waiting',
    'вейтинг': 'waiting',
    
    # Misc
    'хелп': 'help',
    'хэлп': 'help',
    'ок': 'ok',
    'окей': 'okay',
    'йес': 'yes',
    'ноу': 'no',
    'кэнсел': 'cancel',
    'кансел': 'cancel',
    'рижект': 'reject',
    'эпрув': 'approve',
    'эппрув': 'approve',
    'дикляйн': 'decline',
    'деклайн': 'decline',
    'конфёрм': 'confirm',
    'конферм': 'confirm',
    'ченж': 'change',
    'эдит': 'edit',
    'модифай': 'modify',
    'трансформ': 'transform',
    'конверт': 'convert',
    'парс': 'parse',
    'парсить': 'parse',
    'верифай': 'verify',
    'чек': 'check',
    'фикс': 'fix',
    'солв': 'solve',
    'ризолв': 'resolve',
    'хендл': 'handle',
    'хэндл': 'handle',
    'процесс': 'process',
    'анализ': 'analyze',
    'аналайз': 'analyze',
    'сёрч': 'search',
    'фильтр': 'filter',
    'сортировать': 'sort',
    'груп': 'group',
    'групп': 'group',
    'комбайн': 'combine',
    'препенд': 'prepend',
    'инсёрт': 'insert',
    'дупликейт': 'duplicate',
    'дубликат': 'duplicate',
    
    # === File extensions ===
    'ехе': '.exe',
    'ексе': '.exe',
    'экзе': '.exe',
    'джейэс': '.js',
    'джиэс': '.js',
    'тиэс': '.ts',
    'эмди': '.md',
    'маркдаун': '.md',
    'ямлфайл': '.yaml',
    'тхт': '.txt',
    'бат': '.bat',
    'зип': '.zip',
    'тар': '.tar',
    'гз': '.gz',
    'таргз': '.tar.gz',
    'рар': '.rar',
    'севен зип': '.7z',
    'пнг': '.png',
    'джипег': '.jpg',
    'джпг': '.jpg',
    'джипиджи': '.jpg',
    'гиф': '.gif',
    'свг': '.svg',
    'вебп': '.webp',
    'айко': '.ico',
    'пдф': '.pdf',
    'док': '.doc',
    'докс': '.docx',
    'иксэль': '.xlsx',
    'эксель': '.xlsx',
    'цсв': '.csv',
    'сиэсви': '.csv',
    'эсКюЭль': '.sql',
    'сиквел': '.sql',
    'дотенв': '.env',
    'енв': '.env',
    'мейкфайл': 'Makefile',
}
